language: java #or scala => to trigger the build on a 'jvm-otp' box
env:
  - PLAY_VERSION=2.0
before_script:
 - wget http://download.playframework.org/releases/play-${PLAY_VERSION}.zip
 - unzip -q play-${PLAY_VERSION}.zip
script: play-{PLAY_VERSION}/play test
notifications:
  email:
    on_success: always
    on_failure: always